### ISSUE TITLE
Create Sequence Diagram(s) for original P-TYPE

### ISSUE THREAD

**Issue by jxdev8** [nguyensjsu/fa21-202-pied-piper#10]
For the original P-TYPE implementation, capture the sequence diagram(s) representative of the core flows.

**Comment by SAISRAVANICHALASANI2199** [comment]
<img width="987" alt="Screen Shot 2021-12-04 at 12 25 59 PM" src="https://user-images.githubusercontent.com/91631318/144723669-320f0e9f-26a7-4284-8756-f0be7d8aa626.png">

**Comment by hashmithakatta** [comment]
<img width="987" alt="Screen Shot 2021-12-04 at 12 25 59 PM" src="https://user-images.githubusercontent.com/56205828/144723698-a4eb6ea3-e422-49dd-bf4b-0fba4750fbdb.png">
